# Generated by Django 5.2.13 on 2026-04-16 20:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0003_alter_puzzle_challenge'),
        ('gameplay', '0002_remove_gamesession_completed_puzzles_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='gamesession',
            name='completed_puzzles',
            field=models.ManyToManyField(blank=True, related_name='completed_in_sessions', to='challenges.puzzle'),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='end_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='hints_used',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='revealed_answers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='timed_out',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='total_time_seconds',
            field=models.IntegerField(default=0),
        ),
    ]
