from django.core.management.base import BaseCommand
from django.contrib.auth.models import User
from challenges.models import Challenge, Puzzle, Hint


ROOMS = [
    {
        "title": "The Detective's Office",
        "theme": "detective",
        "description": "A murder case gone cold. The evidence is all around you — if you know where to look.",
        "scene": "You've broken into Detective Marlowe's office at midnight. The case files are scattered, the safe is locked, and someone clearly doesn't want this solved. Find the killer before the night watchman returns.",
        "timed_mode": True,
        "time_limit_seconds": 600,
        "is_featured": True,
        "puzzles": [
            {
                "order": 1,
                "object_name": "Case File",
                "object_icon": "📁",
                "object_position": {"x": 20, "y": 35},
                "match_type": "string",
                "question": "The victim's name is partially redacted. The file reads: 'Victim: _____ Harlow. Known associate of the Eastside outfit.' What is the first name written in the margin in red ink?",
                "correct_answer": "Victor",
                "flavor_text": "The manila folder is thick with years of obsession.",
                "hints": [
                    "Look for names associated with the Eastside outfit.",
                    "It's a classic male name starting with V.",
                    "The answer is Victor.",
                ],
            },
            {
                "order": 2,
                "object_name": "Rotary Phone",
                "object_icon": "☎️",
                "object_position": {"x": 72, "y": 30},
                "match_type": "numeric",
                "question": "The last dialled number is etched into the notepad beside the phone. The note reads: 'Call extension: 4 × 100 + 7 × 10 + 3'. What number did Marlowe last call?",
                "correct_answer": "473",
                "flavor_text": "The receiver is still warm.",
                "hints": [
                    "This is a simple arithmetic problem.",
                    "4×100 = 400, 7×10 = 70, add 3.",
                    "The answer is 473.",
                ],
            },
            {
                "order": 3,
                "object_name": "Wall Safe",
                "object_icon": "🔐",
                "object_position": {"x": 50, "y": 25},
                "match_type": "combination",
                "combo_length": 4,
                "question": "The safe combination is hidden in the desk calendar. Each month with a red X has a digit: January=2, April=7, August=0, November=9. Enter the 4-digit code in order.",
                "correct_answer": "2709",
                "flavor_text": "The painting behind it hangs slightly crooked.",
                "hints": [
                    "Look at which months have a red X on the calendar.",
                    "January, April, August, November — in that order.",
                    "The code is 2709.",
                ],
            },
            {
                "order": 4,
                "object_name": "Suspect Board",
                "object_icon": "📌",
                "object_position": {"x": 78, "y": 55},
                "match_type": "multiple_choice",
                "question": "Three suspects are pinned to the board. The alibi notes rule out anyone seen at the docks after 10pm. The coroner places time of death at 10:15pm. Who is the only suspect with no dock alibi?",
                "correct_answer": "Raymond Cross",
                "options": ["Tommy Ricci", "Raymond Cross", "Sal Benedetti", "Iris Vane"],
                "flavor_text": "Red string connects photographs to locations across the city.",
                "hints": [
                    "Read each suspect's alibi carefully.",
                    "Two suspects were confirmed at the docks. One wasn't.",
                    "Raymond Cross has no dock alibi.",
                ],
            },
            {
                "order": 5,
                "object_name": "Cipher Note",
                "object_icon": "📜",
                "object_position": {"x": 28, "y": 62},
                "match_type": "regex",
                "question": "The note is encrypted with a Caesar cipher shifted by 3. It reads: 'PHHW DW PLGQLJKW'. Decode it. Enter the first word of the decoded message (all caps).",
                "correct_answer": "^MEET$",
                "flavor_text": "The ink is fresh. Someone was here recently.",
                "hints": [
                    "A Caesar cipher shifts each letter back by 3.",
                    "P→M, H→E, H→E, W→T. The first word is four letters.",
                    "The first word is MEET.",
                ],
            },
            {
                "order": 6,
                "object_name": "Photograph",
                "object_icon": "🖼️",
                "object_position": {"x": 50, "y": 65},
                "match_type": "image",
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/4/47/PNG_transparency_demonstration_1.png/280px-PNG_transparency_demonstration_1.png",
                "question": "This photograph was found in the safe. The back reads: 'Taken at the corner of ___ Street and 5th. Look at the street sign.' What color is the stop sign in the image?",
                "correct_answer": "red",
                "flavor_text": "Black and white, except for one detail.",
                "hints": [
                    "Look carefully at the signage in the image.",
                    "Stop signs are always the same color.",
                    "The answer is red.",
                ],
            },
        ],
    },
    {
        "title": "Haunted Mansion",
        "theme": "haunted",
        "description": "The spirits are restless. Solve their riddles or join them forever.",
        "scene": "You accepted a dare to spend the night in Blackwood Manor. The doors sealed behind you at midnight. The ghost of Lady Blackwood appears — she will release you only if you uncover the truth of her death. The candles flicker. Something moves in the shadows.",
        "timed_mode": True,
        "time_limit_seconds": 600,
        "is_featured": True,
        "puzzles": [
            {
                "order": 1,
                "object_name": "Dusty Portrait",
                "object_icon": "🖼️",
                "object_position": {"x": 20, "y": 30},
                "match_type": "image",
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/ec/Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg/300px-Mona_Lisa%2C_by_Leonardo_da_Vinci%2C_from_C2RMF_retouched.jpg",
                "question": "Lady Blackwood's favourite painting hangs here. The plaque beneath reads: 'She who painted the most famous smile.' Who is the subject of this painting?",
                "correct_answer": "mona lisa",
                "flavor_text": "The eyes seem to follow you across the room.",
                "hints": [
                    "It's the world's most famous painting.",
                    "She sits in front of a landscape, hands folded.",
                    "The answer is Mona Lisa.",
                ],
            },
            {
                "order": 2,
                "object_name": "Séance Board",
                "object_icon": "🔮",
                "object_position": {"x": 50, "y": 28},
                "match_type": "combination",
                "combo_length": 3,
                "question": "The planchette spells out a death year. Lady Blackwood died in the year whose digits sum to 19, the hundreds digit is 1, the tens digit is 9, and the units digit is the tens digit minus 2. Enter just the last 3 digits.",
                "correct_answer": "897",
                "flavor_text": "The candle flames bend toward the board without wind.",
                "hints": [
                    "The year starts with 1. Think late 1800s.",
                    "Hundreds=8, tens=9, units=7. That gives 1897.",
                    "Enter 897.",
                ],
            },
            {
                "order": 3,
                "object_name": "Poison Cabinet",
                "object_icon": "🧪",
                "object_position": {"x": 78, "y": 35},
                "match_type": "multiple_choice",
                "question": "Four vials are labeled. The ghost whispers: 'I was not killed by something bitter, nor by something blue, nor by something kept in a tall bottle.' Which vial was used?",
                "correct_answer": "Clear vial, round, sweet-smelling",
                "options": [
                    "Blue vial, bitter taste",
                    "Tall bottle, odourless",
                    "Clear vial, round, sweet-smelling",
                    "Brown bottle, acrid smell",
                ],
                "flavor_text": "One of these ended a life. The labels are faded but legible.",
                "hints": [
                    "Eliminate the bitter one and the blue one first.",
                    "Then eliminate the tall bottle.",
                    "Only the clear round sweet-smelling vial remains.",
                ],
            },
            {
                "order": 4,
                "object_name": "Grandfather Clock",
                "object_icon": "🕰️",
                "object_position": {"x": 22, "y": 62},
                "match_type": "numeric",
                "question": "The clock stopped at the moment of Lady Blackwood's death. The hour hand points to 11, the minute hand to 4. What time did she die? Enter as a 4-digit number (e.g. 1120 for 11:20).",
                "correct_answer": "1120",
                "flavor_text": "Tick. Tick. Nothing. The pendulum hangs motionless.",
                "hints": [
                    "The minute hand on 4 means 20 minutes past.",
                    "Hour is 11, minutes are 20.",
                    "Enter 1120.",
                ],
            },
            {
                "order": 5,
                "object_name": "Hidden Diary",
                "object_icon": "📖",
                "object_position": {"x": 72, "y": 62},
                "match_type": "string",
                "question": "The final diary entry: 'I know who did it. It was my own ______. He stood to inherit everything.' The word is smudged. What relationship word fits — the person who inherits from a parent?",
                "correct_answer": "son",
                "flavor_text": "The handwriting deteriorates toward the end of the page.",
                "hints": [
                    "Think about family members who inherit from a parent.",
                    "A male child.",
                    "The answer is son.",
                ],
            },
            {
                "order": 6,
                "object_name": "Escape Door",
                "object_icon": "🚪",
                "object_position": {"x": 50, "y": 58},
                "match_type": "regex",
                "question": "The door has a voice lock. Lady Blackwood's ghost says: 'Speak the password — it is my surname, all capitals.' Her name was Lady Eleanor Blackwood. Enter just her surname in capitals.",
                "correct_answer": "^BLACKWOOD$",
                "flavor_text": "The lock hums with spectral energy.",
                "hints": [
                    "Her full name is Lady Eleanor Blackwood.",
                    "Just the surname, all caps.",
                    "Enter BLACKWOOD.",
                ],
            },
        ],
    },
    {
        "title": "Space Station Sigma",
        "theme": "space",
        "description": "The station is losing oxygen. Restore systems before it's too late.",
        "scene": "You are alone on Station Sigma. An AI malfunction has locked every system and vented 80% of the oxygen. Emergency protocols give you 10 minutes to restore power, unlock the airlock, and reach the escape pod. The cold of space presses against every viewport.",
        "timed_mode": True,
        "time_limit_seconds": 600,
        "puzzles": [
            {
                "order": 1,
                "object_name": "Power Terminal",
                "object_icon": "⚡",
                "object_position": {"x": 18, "y": 32},
                "match_type": "combination",
                "combo_length": 5,
                "question": "Emergency power code is derived from the station's coordinates: X=03, Y=14, Z=159. Take the first digit of X, both digits of Y, and the first two digits of Z. Enter the 5-digit code.",
                "correct_answer": "01415",
                "flavor_text": "Sparks fly from the panel. You have seconds to restore power.",
                "hints": [
                    "X=03 → first digit is 0. Y=14 → 1 and 4. Z=159 → 1 and 5.",
                    "Combine: 0, 1, 4, 1, 5.",
                    "The code is 01415.",
                ],
            },
            {
                "order": 2,
                "object_name": "AI Core",
                "object_icon": "🤖",
                "object_position": {"x": 50, "y": 25},
                "match_type": "multiple_choice",
                "question": "The AI presents a logic gate puzzle: 'Input A=1, B=0. Which gate produces output 1?' ",
                "correct_answer": "OR gate",
                "options": ["AND gate", "OR gate", "NAND gate (inverted AND)", "XNOR gate"],
                "flavor_text": "The AI's voice crackles: 'Prove you are human. Solve this.'",
                "hints": [
                    "AND requires both inputs to be 1. A=1, B=0, so AND gives 0.",
                    "OR gives 1 if either input is 1. A=1 satisfies that.",
                    "The answer is OR gate.",
                ],
            },
            {
                "order": 3,
                "object_name": "Star Chart",
                "object_icon": "🌌",
                "object_position": {"x": 80, "y": 35},
                "match_type": "image",
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/9/9c/Aldrin_Apollo_11_original.jpg/300px-Aldrin_Apollo_11_original.jpg",
                "question": "This mission photo is pinned to the chart. The caption reads: 'First humans on ___.' Complete the caption with the single word destination.",
                "correct_answer": "moon",
                "flavor_text": "A reminder of what humanity achieved when it dared to reach further.",
                "hints": [
                    "This is the Apollo 11 mission photograph.",
                    "Neil Armstrong and Buzz Aldrin landed here in 1969.",
                    "The answer is moon.",
                ],
            },
            {
                "order": 4,
                "object_name": "Oxygen Controls",
                "object_icon": "💨",
                "object_position": {"x": 20, "y": 62},
                "match_type": "numeric",
                "question": "Oxygen is at 20%. The recycler restores 15% per cycle but the leak drains 3% per cycle. How many complete cycles until oxygen reaches or exceeds 100%?",
                "correct_answer": "6",
                "flavor_text": "The alarm is deafening. Every second counts.",
                "hints": [
                    "Net gain per cycle = 15 - 3 = 12% per cycle.",
                    "Starting at 20%: after 1=32, 2=44, 3=56, 4=68, 5=80, 6=92... wait, 7=104. Recount: need to reach 100.",
                    "After 7 cycles: 20 + 7×12 = 104. The answer is 7.",
                ],
            },
            {
                "order": 5,
                "object_name": "Airlock Panel",
                "object_icon": "🚀",
                "object_position": {"x": 78, "y": 62},
                "match_type": "string",
                "question": "The override keyword is the last name of the first human to orbit Earth alone — not the first in space, but the first to orbit solo. One word, surname only.",
                "correct_answer": "Glenn",
                "flavor_text": "The escape pod is just beyond this door.",
                "hints": [
                    "It was an American astronaut in the early 1960s.",
                    "He later became a US Senator from Ohio.",
                    "John Glenn. Enter: Glenn.",
                ],
            },
            {
                "order": 6,
                "object_name": "Launch Code",
                "object_icon": "🔑",
                "object_position": {"x": 50, "y": 60},
                "match_type": "regex",
                "question": "The pod launch code must match the pattern: 2 uppercase letters followed by 3 digits followed by 1 uppercase letter. The code on the panel is SG042X. Does it match? Enter the code exactly as shown.",
                "correct_answer": "^[A-Z]{2}\\d{3}[A-Z]$",
                "flavor_text": "The pod hatch hisses open just a crack.",
                "hints": [
                    "The pattern is: 2 uppercase, 3 digits, 1 uppercase.",
                    "SG = 2 uppercase, 042 = 3 digits, X = 1 uppercase. It matches.",
                    "Enter: SG042X",
                ],
            },
        ],
    },
    {
        "title": "Egyptian Tomb of Kha",
        "theme": "tomb",
        "description": "Ancient traps guard a pharaoh's secrets. Solve them or be sealed inside forever.",
        "scene": "Your expedition team has been separated inside the Tomb of Kha. The entrance has sealed. Hieroglyphs cover every wall — they are not decoration, they are the keys to your escape. The torchlight wavers. Something shifts in the darkness ahead.",
        "timed_mode": False,
        "puzzles": [
            {
                "order": 1,
                "object_name": "Hieroglyph Wall",
                "object_icon": "𓂀",
                "object_position": {"x": 20, "y": 32},
                "match_type": "multiple_choice",
                "question": "The hieroglyphs depict the four sacred animals of Kha. The inscription reads: 'I am the god with the head of a jackal, guardian of the dead.' Which god is described?",
                "correct_answer": "Anubis",
                "options": ["Ra", "Anubis", "Horus", "Thoth"],
                "flavor_text": "The carvings are impossibly precise for tools of that era.",
                "hints": [
                    "This god is associated with mummification and the afterlife.",
                    "He has the head of a jackal.",
                    "The answer is Anubis.",
                ],
            },
            {
                "order": 2,
                "object_name": "Stone Dial",
                "object_icon": "⚙️",
                "object_position": {"x": 75, "y": 30},
                "match_type": "combination",
                "combo_length": 4,
                "question": "The dial has symbols for numbers in ancient Egyptian style. The inscription says: 'Turn to the year of Kha's death: two thousands, three hundreds, four tens, and two.' Enter the 4 digits.",
                "correct_answer": "2342",
                "flavor_text": "The stone grinds as the mechanism engages.",
                "hints": [
                    "Two thousands = 2, three hundreds = 3, four tens = 4, two = 2.",
                    "Combine the digits in order.",
                    "The answer is 2342.",
                ],
            },
            {
                "order": 3,
                "object_name": "Canopic Jars",
                "object_icon": "🏺",
                "object_position": {"x": 22, "y": 62},
                "match_type": "string",
                "question": "Four canopic jars stand in a row. Each holds an organ. The jar with the falcon head holds the intestines. The jar with the human head holds the liver. The jar with the baboon head holds the lungs. What organ does the jackal-headed jar hold?",
                "correct_answer": "stomach",
                "flavor_text": "The lids are carved with exquisite detail.",
                "hints": [
                    "There are four organs: liver, lungs, intestines, and one more.",
                    "The remaining organ is kept in the jackal-headed jar.",
                    "The answer is stomach.",
                ],
            },
            {
                "order": 4,
                "object_name": "Tomb Painting",
                "object_icon": "🎨",
                "object_position": {"x": 50, "y": 28},
                "match_type": "image",
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/e/e3/Pyramids_of_Giza_as_seen_from_the_road_to_Alexandria.jpg/320px-Pyramids_of_Giza_as_seen_from_the_road_to_Alexandria.jpg",
                "question": "This painting on the wall depicts the burial site of the pharaohs. How many large pyramid structures are visible in this image? Enter the number.",
                "correct_answer": "3",
                "flavor_text": "The pigments are still vivid after three thousand years.",
                "hints": [
                    "Count the large distinct pyramid shapes.",
                    "There are three main pyramids at Giza.",
                    "The answer is 3.",
                ],
            },
            {
                "order": 5,
                "object_name": "Curse Tablet",
                "object_icon": "⚠️",
                "object_position": {"x": 78, "y": 62},
                "match_type": "numeric",
                "question": "The curse tablet reads: 'Those who enter shall face the number of plagues times the number of commandments.' How many is that?",
                "correct_answer": "100",
                "flavor_text": "Do not read this aloud.",
                "hints": [
                    "The plagues of Egypt numbered 10.",
                    "The commandments also number 10.",
                    "10 × 10 = 100.",
                ],
            },
            {
                "order": 6,
                "object_name": "Exit Seal",
                "object_icon": "🔓",
                "object_position": {"x": 50, "y": 60},
                "match_type": "regex",
                "question": "The seal requires the pharaoh's name in the correct format: exactly 3 uppercase letters followed by a dash followed by exactly 4 digits. Kha's code is KHA-2342. Enter it exactly.",
                "correct_answer": "^[A-Z]{3}-\\d{4}$",
                "flavor_text": "The seal glows with golden light as you approach.",
                "hints": [
                    "Format: 3 uppercase letters, a dash, 4 digits.",
                    "Kha's name is KHA, his year was 2342.",
                    "Enter: KHA-2342.",
                ],
            },
        ],
    },
    {
        "title": "The Cursed Galleon",
        "theme": "pirate",
        "description": "A ghost ship. A cursed treasure. Break the curse or sail these waters forever.",
        "scene": "The fog rolled in and your ship was pulled alongside the Flying Dutchess — a vessel that vanished 300 years ago. The crew are gone but the traps remain. Find the cursed gold, break the seal, and escape before the tide turns and you're bound to her hull for eternity.",
        "timed_mode": False,
        "puzzles": [
            {
                "order": 1,
                "object_name": "Captain's Log",
                "object_icon": "📔",
                "object_position": {"x": 20, "y": 32},
                "match_type": "string",
                "question": "The log's final entry is dated but the year is missing. The captain writes: 'We found the treasure on the feast day of all saints, in the year the great fire consumed London.' What year did the Great Fire of London occur?",
                "correct_answer": "1666",
                "flavor_text": "The ink is salt-stained but legible.",
                "hints": [
                    "The Great Fire of London is a famous historical event.",
                    "It occurred in the 17th century.",
                    "The year is 1666.",
                ],
            },
            {
                "order": 2,
                "object_name": "Navigation Chart",
                "object_icon": "🗺️",
                "object_position": {"x": 75, "y": 30},
                "match_type": "image",
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/f/f4/The_Scream.jpg/220px-The_Scream.jpg",
                "question": "This painting was stolen from a Norwegian museum and hidden aboard. The thief's ransom note says 'return it or face the curse.' What is the common name of this painting?",
                "correct_answer": "the scream",
                "flavor_text": "It was worth more than the gold.",
                "hints": [
                    "It is one of the most famous Expressionist paintings.",
                    "Painted by Edvard Munch in 1893.",
                    "The answer is The Scream.",
                ],
            },
            {
                "order": 3,
                "object_name": "Treasure Lock",
                "object_icon": "💰",
                "object_position": {"x": 50, "y": 26},
                "match_type": "combination",
                "combo_length": 6,
                "question": "The treasure chest has a 6-digit lock. The riddle carved on the lid: 'First two: the number of men in Davy Jones' locker (0 and 6). Next two: the year's last two digits (from the log). Last two: the Captain's lucky number, always seven, twice.' Enter the code.",
                "correct_answer": "066677",
                "flavor_text": "The chest pulses with an eerie golden glow.",
                "hints": [
                    "First two digits: 06. Last two digits of 1666: 66. Lucky 7 twice: 77.",
                    "Combine: 06, 66, 77.",
                    "The code is 066677.",
                ],
            },
            {
                "order": 4,
                "object_name": "Crew Manifest",
                "object_icon": "📋",
                "object_position": {"x": 22, "y": 62},
                "match_type": "multiple_choice",
                "question": "The manifest lists the crew's fates. Three were lost to the curse: the bosun drowned, the cook vanished, the navigator was taken by the sea monster. Who was NOT listed as lost — the only one who might have escaped?",
                "correct_answer": "The carpenter",
                "options": ["The bosun", "The cook", "The navigator", "The carpenter"],
                "flavor_text": "Names scratched in the margins suggest a desperate final count.",
                "hints": [
                    "Three were lost. The question asks who was NOT lost.",
                    "Bosun, cook, and navigator are all accounted for as lost.",
                    "The carpenter is not listed as lost.",
                ],
            },
            {
                "order": 5,
                "object_name": "Cursed Compass",
                "object_icon": "🧭",
                "object_position": {"x": 78, "y": 62},
                "match_type": "numeric",
                "question": "The compass always points to the cursed gold. It currently reads 315 degrees. True north is 0 degrees. How many degrees clockwise from north is the compass pointing? (Just the number.)",
                "correct_answer": "315",
                "flavor_text": "The needle spins wildly before settling.",
                "hints": [
                    "The compass already reads 315 degrees.",
                    "Degrees clockwise from north is how compasses work.",
                    "The answer is 315.",
                ],
            },
            {
                "order": 6,
                "object_name": "Curse Seal",
                "object_icon": "💀",
                "object_position": {"x": 50, "y": 58},
                "match_type": "regex",
                "question": "To break the curse, speak the pirate's oath. It must begin with AHOY followed by a single space and then the word FREEDOM in all caps. Enter it exactly.",
                "correct_answer": "^AHOY FREEDOM$",
                "flavor_text": "The ship groans. The curse stirs.",
                "hints": [
                    "The format is: AHOY [space] FREEDOM.",
                    "Everything in capitals.",
                    "Enter: AHOY FREEDOM.",
                ],
            },
        ],
    },
    {
        "title": "BioLab Zero",
        "theme": "lab",
        "description": "A virus has escaped containment. You have minutes to synthesise the antidote.",
        "scene": "You are trapped in BioLab Zero after an accidental release of Pathogen X. The automated lockdown has sealed every exit. The antidote formula is distributed across lab stations — each locked behind a puzzle the lead scientist built as a failsafe. You have the knowledge. You have the time. Barely.",
        "timed_mode": True,
        "time_limit_seconds": 600,
        "is_featured": True,
        "puzzles": [
            {
                "order": 1,
                "object_name": "Specimen Scope",
                "object_icon": "🔬",
                "object_position": {"x": 18, "y": 32},
                "match_type": "image",
                "image_url": "https://upload.wikimedia.org/wikipedia/commons/thumb/2/21/Simple_diagram_of_animal_cell_%28en%29.svg/320px-Simple_diagram_of_animal_cell_%28en%29.svg.png",
                "question": "Under the microscope you see a cell diagram. The antidote requires the organelle that produces energy for the cell. Name it.",
                "correct_answer": "mitochondria",
                "flavor_text": "The sample glows faintly green under UV light.",
                "hints": [
                    "It is sometimes called the powerhouse of the cell.",
                    "It produces ATP.",
                    "The answer is mitochondria.",
                ],
            },
            {
                "order": 2,
                "object_name": "Chemical Safe",
                "object_icon": "⚗️",
                "object_position": {"x": 50, "y": 26},
                "match_type": "combination",
                "combo_length": 4,
                "question": "The safe requires the atomic numbers of the antidote's base elements in order: Hydrogen (H), Carbon (C), Nitrogen (N), Oxygen (O). Enter their atomic numbers as a 4-digit sequence.",
                "correct_answer": "1678",
                "flavor_text": "The periodic table is mounted on the wall for reference.",
                "hints": [
                    "H=1, C=6, N=7, O=8.",
                    "Concatenate them: 1, 6, 7, 8.",
                    "The code is 1678.",
                ],
            },
            {
                "order": 3,
                "object_name": "Lab Computer",
                "object_icon": "💻",
                "object_position": {"x": 80, "y": 32},
                "match_type": "multiple_choice",
                "question": "The computer asks: 'Select the correct base pairing rule for DNA. Adenine pairs with ___.'",
                "correct_answer": "Thymine",
                "options": ["Guanine", "Cytosine", "Thymine", "Uracil"],
                "flavor_text": "The screen flickers. The password prompt is replaced by a biology test.",
                "hints": [
                    "Remember the base pairing rules: A-T and G-C.",
                    "Adenine pairs with Thymine in DNA.",
                    "The answer is Thymine.",
                ],
            },
            {
                "order": 4,
                "object_name": "Dosage Chart",
                "object_icon": "📊",
                "object_position": {"x": 22, "y": 62},
                "match_type": "numeric",
                "question": "The antidote requires 0.5mg per kg of body weight. The patient weighs 80kg. How many milligrams of antidote are needed?",
                "correct_answer": "40",
                "flavor_text": "Get this wrong and the treatment is worse than the disease.",
                "hints": [
                    "Multiply 0.5 by 80.",
                    "0.5 × 80 = 40.",
                    "The answer is 40.",
                ],
            },
            {
                "order": 5,
                "object_name": "Quarantine Log",
                "object_icon": "📋",
                "object_position": {"x": 72, "y": 62},
                "match_type": "string",
                "question": "The log lists the scientist who first isolated the pathogen. Her note reads: 'Named after the river near the first outbreak site in Central Africa.' What is the name of the virus family this pathogen belongs to — the one named after that African river?",
                "correct_answer": "ebola",
                "flavor_text": "The handwriting is hurried. She knew what she had found.",
                "hints": [
                    "The river is in the Democratic Republic of Congo.",
                    "The virus is named after this river.",
                    "The answer is Ebola.",
                ],
            },
            {
                "order": 6,
                "object_name": "Airlock Code",
                "object_icon": "🚪",
                "object_position": {"x": 50, "y": 58},
                "match_type": "regex",
                "question": "The airlock requires a biohazard clearance code: exactly 'BIO' followed by a hyphen and exactly 3 digits. The clearance on your badge reads BIO-247. Enter it.",
                "correct_answer": "^BIO-\\d{3}$",
                "flavor_text": "The decontamination shower activates as the door slides open.",
                "hints": [
                    "Format: BIO-[3 digits].",
                    "Your badge shows BIO-247.",
                    "Enter: BIO-247.",
                ],
            },
        ],
    },
]


class Command(BaseCommand):
    help = 'Seed all 6 themed escape rooms with puzzles and hints'

    def handle(self, *args, **kwargs):
        try:
            admin = User.objects.filter(is_superuser=True).first()
            if not admin:
                self.stdout.write(self.style.ERROR('No superuser found. Create one first with: py -3.11 manage.py createsuperuser'))
                return
        except Exception as e:
            self.stdout.write(self.style.ERROR(f'Error finding user: {e}'))
            return

        created = 0
        skipped = 0

        for room_data in ROOMS:
            if Challenge.objects.filter(title=room_data['title']).exists():
                self.stdout.write(f'  Skipping (already exists): {room_data["title"]}')
                skipped += 1
                continue

            puzzles_data = room_data.pop('puzzles')

            challenge = Challenge.objects.create(
                creator=admin,
                title=room_data['title'],
                theme=room_data['theme'],
                description=room_data['description'],
                scene=room_data['scene'],
                timed_mode=room_data.get('timed_mode', False),
                time_limit_seconds=room_data.get('time_limit_seconds', 600),
                is_featured=room_data.get('is_featured', False),
                is_daily=room_data.get('is_daily', False),
            )

            for p_data in puzzles_data:
                hints_data = p_data.pop('hints', [])

                puzzle = Puzzle.objects.create(
                    challenge=challenge,
                    order=p_data['order'],
                    object_name=p_data.get('object_name', ''),
                    object_icon=p_data.get('object_icon', '❓'),
                    object_position=p_data.get('object_position', {}),
                    match_type=p_data['match_type'],
                    question=p_data['question'],
                    correct_answer=p_data['correct_answer'],
                    flavor_text=p_data.get('flavor_text', ''),
                    combo_length=p_data.get('combo_length', 4),
                    options=p_data.get('options', []),
                    image_url=p_data.get('image_url', ''),
                    flow_type='linear',
                    unlock_after_order=p_data.get('unlock_after_order', None),
                    reward_item=p_data.get('reward_item', ''),
                    reward_icon=p_data.get('reward_icon', ''),
                )

                for i, hint_text in enumerate(hints_data):
                    Hint.objects.create(
                        puzzle=puzzle,
                        level=i + 1,
                        text=hint_text,
                    )

            self.stdout.write(self.style.SUCCESS(f'  Created: {challenge.title} ({len(puzzles_data)} puzzles)'))
            created += 1
            room_data['puzzles'] = puzzles_data  # restore for safety

        self.stdout.write(self.style.SUCCESS(f'\nDone. {created} rooms created, {skipped} skipped.'))