# Generated by Django 5.2.13 on 2026-04-15 01:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='challenge',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='creator',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='description',
        ),
        migrations.RemoveField(
            model_name='challenge',
            name='title',
        ),
        migrations.RemoveField(
            model_name='puzzle',
            name='prompt',
        ),
        migrations.AddField(
            model_name='puzzle',
            name='branches',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='flow_type',
            field=models.CharField(default='linear', max_length=20),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='match_type',
            field=models.CharField(default='string', max_length=20),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='next_puzzle',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='challenges.puzzle'),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='time_limit_seconds',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.challenge'),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='correct_answer',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='order',
            field=models.IntegerField(default=0),
        ),
        migrations.CreateModel(
            name='Hint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField()),
                ('text', models.TextField()),
                ('puzzle', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='challenges.puzzle')),
            ],
        ),
    ]
