# Generated by Django 5.2.13 on 2026-04-16 15:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0002_remove_challenge_created_at_remove_challenge_creator_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='puzzle',
            name='challenge',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='puzzles', to='challenges.challenge'),
        ),
    ]
