# Generated by Django 5.2.13 on 2026-05-04 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0004_challenge_created_at_challenge_creator_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='daily_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_daily',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='is_featured',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='challenge',
            name='scene',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='flavor_text',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='image_url',
            field=models.URLField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='options',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='time_limit_seconds',
            field=models.IntegerField(default=300),
        ),
        migrations.AlterField(
            model_name='puzzle',
            name='match_type',
            field=models.CharField(choices=[('string', 'Exact Match'), ('regex', 'Pattern Match'), ('numeric', 'Numeric Match'), ('multiple_choice', 'Multiple Choice'), ('combination', 'Combination Lock'), ('image', 'Image Puzzle')], default='string', max_length=20),
        ),
    ]
