# Generated by Django 5.2.13 on 2026-05-04 01:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0005_challenge_daily_date_challenge_is_daily_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='puzzle',
            name='combo_length',
            field=models.IntegerField(default=4),
        ),
    ]
