# Generated by Django 5.2.13 on 2026-05-04 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('challenges', '0006_puzzle_combo_length'),
    ]

    operations = [
        migrations.AddField(
            model_name='challenge',
            name='theme',
            field=models.CharField(choices=[('detective', 'Detective Office'), ('haunted', 'Haunted Mansion'), ('space', 'Space Station'), ('tomb', 'Egyptian Tomb'), ('pirate', 'Pirate Ship'), ('lab', 'Secret Lab')], default='detective', max_length=20),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='object_icon',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='object_name',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='object_position',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='reward_icon',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='reward_item',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='puzzle',
            name='unlock_after_order',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
